### ISSUE TITLE
Field guide section on Delta Scuti pulsators

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#10]
A field guide entry of Delta Scuti variables is needed

Feature Summary
write a description, show an example light curve, and add the golden set

Usage / behavior
similar to RRLyr page

Implementation details
See https://scope.ztf.dev/developer.html#contributing-field-guide-sections

**Comment by mcoughlin** [comment]
For reference, the Zooniverse field guide has:

## [delta Scuti](https://en.wikipedia.org/wiki/Delta_Scuti_variable)
 - Small amplitude (between 0.05 and 0.3)
 - Short periods (log Period between -1.5 to -0.5)
 - smooth, sawtooth variations (blue/green filters show stronger sawtooth pattern)

delta Scuti variables are classic pulsating stars (i.e., they are stars passing through the [instability strip](https://en.wikipedia.org/wiki/Instability_strip)). As these stars expand and contract (i.e. pulsate) their size and temperature changes leading to regular, smooth variations in their brightness. delta Scuti stars are smaller than both Cepheids and RR Lyrae stars, which leads to a short period of oscillations (typically anywhere between 0.03 days and 0.3 days).
