### ISSUE TITLE
Field guide section on Beta Lyr binaries

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#12]
A field guide entry of Beta Lyr binaries is needed

Feature Summary
write a description, show an example light curve, and add the golden set

Usage / behavior
similar to RRLyr page

Implementation details
See https://scope.ztf.dev/developer.html#contributing-field-guide-sections

**Comment by mcoughlin** [comment]
For reference, the Zooniverse field guide has:

## [semi-detached eclipsing binary](https://en.wikipedia.org/wiki/Beta_Lyrae_variable) (EB)
 - Range of amplitudes (~0.2 to >1 mag)
 - Intermediate periods (log Period between -0.5 and 1.4)
 - Round or sinusoidal light curves, with imposed "V-shape" dips in the phase folded light curve

Semi-detached eclipsing binaries (also called [beta Lyrae variables](https://en.wikipedia.org/wiki/Beta_Lyrae_variable)) are binary star systems (i.e. two stars that are in orbit around each other) that are aligned such that they eclipse each other relative to our line of sight from the Earth. Unlike detached EBs, semi-detatched systems are so close to each other that the shape of (at least one of) the stars in the system are distorted, giving rise to the smooth periodic variations even when the system is not eclipsing. 

Any type of star can be in an eclipsing binary (so they may be small, large, hot, cool, etc.), which in turn can lead to a large range in eclipse amplitudes (though typically these are between 0.1 and ~1 mag, with most in the ~0.3 to 0.75 mag range) or eclipse periods (though our observations are typically only sensitive to periods between 0.1 to ~20 days).

**Comment by dmitryduev** [comment]
Done in #24, closing.
