### ISSUE TITLE
Decide on file format to use for training set

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#128]
While we currently save/load training sets in CSV format, it may be more economical to use another format, e.g. hdf5 or pickle. We can discuss here the best option to proceed with.

**Comment by bfhealy** [comment]
@mcoughlin I've been working on saving the training set to an hdf5 file, but I've found that this format struggles with the arrays contained in the dmdt column of our dataframe. The arrays get pickled upon saving, and the code gives the user a performance warning. The resulting file size ends up being not much smaller than a csv file. 

I've been looking into parquet as an alternative format that natively supports having a column of arrays. There is a ~4x reduction in file size using parquet instead of hdf5. Do you think parquet would be a preferable format to use?

**Comment by mcoughlin** [comment]
@bfhealy yes, another popular format indeed. I think as long as that same PR adds some documentation for reading the data using common tools, should be good

**Comment by bfhealy** [comment]
@mcoughlin Ok, sounds good!
