### ISSUE TITLE
'Binary star' vs 'eclipsing' labels

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#133]
The golden dataset has both ontological "binary star" and phenomenological "eclipsing" labels. There are ~38,000 nonzero eclipsing labels and ~29,000 nonzero binary star labels. ~97% of sources labeled as binary star are also labeled as eclipsing, while ~75% of eclipsing sources are also labeled as binary star. Logically, I would expect the opposite - that while all eclipsing stars are binaries (or multiples, at least), not all binary stars should show eclipses. But if light curves were the only data used to assign these labels, I would expect approximately a one-to-one mapping between eclipses and binary stars with a small number of exceptions, e.g. for ellipsoidal variables.

When posting to fritz, the binary star label maps to the sitewide taxonomy's Eclipsing label (capital E), while the eclipsing label maps to the eclipsing label in the scope phenomenological taxonomy. With the binary star label effectively a subset of the eclipsing label in the golden dataset, and considering the logic above, maybe it is appropriate to merge these labels into one. We could then map this merged label to both the phenomenological eclipsing and ontological Eclipsing labels on fritz. This might improve our training process and remove an ambiguity in the training set labels.

**Comment by bfhealy** [comment]
The DNN training currently uses an expanded set of features for ontological classifiers (including `binary star`, see #141). In theory, this allows for a fundamental difference between the phenomenological `eclipsing` and ontological `binary star` labels. However, the DNN's recognition of this difference depends on the training set and how it was constructed by the human classifiers. Since `binary star` is almost entirely a subset of `eclipsing`, it may still be ok to merge the classes.

**Comment by AshishMahabal** [comment]
Can you clarify what you mean by merging the two classes? The eclipsing class would include binaries that do not belong to W Uma, B Lyrae, RS CVn etc. current definite binaries (sub-classes of the ontological binary star class). Ideally, when we have classified everything and understood them, every object currently under eclipsing will be under a subclass of binary star, or under another branch (e.g. planet candidate).

**Comment by bfhealy** [comment]
The issue I'm thinking about here stems from the lack of a `binary star` label in the sitewide taxonomy that we're using on Fritz for the ontological classes. Instead, there is an `Eclipsing` label to which I mapped the `binary star` label when uploading golden dataset sources. My thought process behind this mapping was that even though Scope's `binary star` label allows for non-eclipsing sources, in the golden dataset 97% of `binary star` sources also have the phenomenological `eclipsing` label.

Going forward with the training and inference, I'm wondering how to treat the `binary star` label, since it will likely serve as a proxy for eclipsing sources (based on the training set). 'Merging' the classes is perhaps not the right word; instead I should say I'm considering treating the upcoming newly classified  `binary star` sources as `Eclipsing` in the sitewide taxonomy.
