### ISSUE TITLE
Add WandB group name to training runs

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#136]
As we run multiple iterations of training for each binary classifier, we will want to compare the different runs while maintaining organization between them. I think we should associate each run with a group that shares a common DNN architecture, hyperparameters and training set using e.g. `wandb.init(group="experiment_1", job_type="eval")` (https://docs.wandb.ai/guides/track/advanced/grouping).

**Comment by AshishMahabal** [comment]
Good idea

**Comment by guiga004** [comment]
@bfhealy - is there a default group and job_type we want to use when not specified?

**Comment by bfhealy** [comment]
@guiga004 Perhaps the default group could be 'experiment' and job_type 'train'?
