### ISSUE TITLE
Feature domain for phenomenological and ontological classes

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#141]
Currently, DNN training on our phenomenological classes uses 40 features generated from the ZTF light curves. The ontological classifiers are trained on all of those features along with 34 more. These additional features consist of AllWISE, Gaia and PanStarrs magnitudes along with the ra, dec, ccd and quadrant of the source.

How should we proceed with these feature domains going forward? I don't think the coordinates and silicon position of the source should be part of the training (especially for the ontological branch where they're used now), since those features should not inform the intrinsic nature of the source.

Also, the inclusion of additional features for the ontological training means that the distinction between the phenomenological `eclipsing` and ontological `binary star` classes may be more complex that mentioned in #133. It would be helpful to know how the human classifiers treated these two classes during their labeling.

**Comment by AshishMahabal** [comment]
I agree that ra, dec, ccd and quadrant should not be part of the training. I am surprised they were. Were they explicitly used?

**Comment by bfhealy** [comment]
Yes, in config.yaml for `features:` they are explicitly listed under the `ontological:` header. They were commented out in an older-looking header in the list (`ontological_d13:`), but in the one that's currently being used by the training, they are uncommented.

**Comment by AshishMahabal** [comment]
They should definitely not be used, In xgboost I have not used them, and based on the old header you mention, I am certain that Dima wouldn't have used those. We were pulling parameters like quad because at one point we were looking for bogus objects as a function of quads to understand the types of boguses.

**Comment by bfhealy** [comment]
That makes sense, I can see how those features would be useful for identifying bogus sources. I'll comment out the inclusion of ra, dec, ccd and quad in the ontological feature list.

**Comment by bfhealy** [comment]
This issue is also specifically relevant to the AGN class, for which the Gaia parallax should not be applicable.
