### ISSUE TITLE
Lightcurve y-range is reverse for WUma

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#17]
The lightcurve figure y-limits are reversed for the WUma figure

**Describe the bug**
for the example lightcurve figure, the y-limits are reversed. A better method to determine the y-limits are needed.

**To Reproduce**
see the WUma fieldguide.

**Expected behavior**
The y-limits of the lightcurve should show correct range, with high magnitudes at the bottom and low magnitudes at the top. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10774087/112553179-3dad5780-8d81-11eb-8e46-fe4df67a5486.png)

**Comment by dmitryduev** [comment]
Fixed in #19, closing.
