### ISSUE TITLE
Incorporate ztfperiodic code into scope

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#189]
The code that generates features for scope currently resides in the [ztfperiodic](https://github.com/mcoughlin/ztfperiodic) repository. Some major parts of the code are as follows:
- Basic statistics are generated by [lcstats.py](https://github.com/mcoughlin/ztfperiodic/blob/master/ztfperiodic/lcstats.py#L262)
- Periodicity stats are generated by [periodsearch.py](https://github.com/mcoughlin/ztfperiodic/blob/master/ztfperiodic/periodsearch.py#L200)
    - This process runs on GPUs via the [periodfind](https://github.com/ejaszewski/periodfind) repo
    - Fourier stats from this process are also generated by [lcstats.py](https://github.com/mcoughlin/ztfperiodic/blob/master/ztfperiodic/lcstats.py#L331)
- The above results are combined by [ztfperiodic_period_search.py](https://github.com/mcoughlin/ztfperiodic/blob/master/bin/ztfperiodic_period_search.py)

The goal is to incorporate this code into scope so we can generate features with the same codebase that we already use for the other parts of the project. This will require us to update scope dependencies, clean up the current code, and decide on how the new code should be organized within the scope repository.

**Comment by bfhealy** [comment]
@mcoughlin Do you think it is a good idea to commit the existing ztfperiodic code above to scope and modify it after? This would make it easier to keep track of changes to the current code.

**Comment by mcoughlin** [comment]
@bfhealy yeah, just make sure to run the relevant pre-commit on the relevant functions :)
