### ISSUE TITLE
Uploading training sources without good photometry

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#219]
Some of the new sources that we will be adding to the golden training set are either missing ZTF photometry entirely, or all of their photometric points are flagged and thus get dropped before getting uploaded. Should these sources still be uploaded to the training set in the hope of future data releases providing good photometry?

**Comment by mcoughlin** [comment]
@bfhealy My intuition is that the answer is no, as it seems liable to contaminate the training.

**Comment by bfhealy** [comment]
@mcoughlin That makes sense to me - it will take a few minor tweaks to the upload process to exclude these sources.
