### ISSUE TITLE
Imputing features for inference sources

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#233]
When imputing features for inference sources, we can either:
(1) always use the mean/median/KNN regression results for sources in the training dataset, or
(2) self-impute using stats computed from each batch of inference sources (usually 100,000 sources in a batch). 

Option (1) has the advantage of a uniform approach for all inference fields/batches, but if there are significant discrepancies between the training and inference source populations, the imputed values may be inaccurate. Option (2) tailors imputation to the characteristics of each individual batch of sources at the cost of a less uniform approach. Our code can already support both approaches - which do you think is preferable @AshishMahabal, @mcoughlin?

(Regardless of the choice above, all features will be scaled using identical statistics to ensure consistency between training and inference).

**Comment by mcoughlin** [comment]
(2) feels better, especially as I assume the batches will be in the same field and therefore similar parts of the sky.

**Comment by AshishMahabal** [comment]
I agree.

**Comment by bfhealy** [comment]
Thank you both!
