### ISSUE TITLE
Separate some Kowalski queries from main feature generation script

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#308]
For fields/ccd/quads near the galactic plane with many sources, the `drop_close_bright_stars` portion of our feature generation script (querying Gaia EDR3 for sources within 300 arcsec of each ZTF source) can take several hours. This is a significant amount of time where GPUs are not needed, but are currently being used anyway. If we ran this part of feature generation separately on CPUs and saved the results, we could reduce compute cost and dedicate more of the 48-hour maximum GPU walltime to period finding.

**Comment by mcoughlin** [comment]
@bfhealy This cross-match is also done in Kowalski? What is slow exactly?

**Comment by bfhealy** [comment]
@mcoughlin The below cone search query (run for 10,000 sources at a time by default) is what's holding up that part of the code. The cone radius is 300 arcsec, and in dense regions of the sky the query returns a lot of EDR3 sources brighter than 13th G magnitude. Earlier in the script, it may help to filter ZTF sources using e.g. `nobs > 20` to avoid running the Gaia query for sources without the requisite number of photometry points.

```
# Get Gaia EDR3 ID, G mag, BP-RP, and coordinates
        query = {
            "query_type": "cone_search",
            "query": {
                "object_coordinates": {
                    "radec": dict(zip(id_slice, radec_geojson.transpose().tolist())),
                    "cone_search_radius": query_radius_arcsec,
                    "cone_search_unit": 'arcsec',
                },
                "catalogs": {
                    catalog: {
                        # Select sources brighter than G magnitude 13:
                        # -Conversion to Tycho mags only good for G < 13
                        # -Need for exclusion radius only for stars with B <~ 13
                        # -For most stars, if G > 13, B > 13
                        "filter": {"phot_g_mean_mag": {"$lt": 13.0}},
                        "projection": {
                            "phot_g_mean_mag": 1,
                            "bp_rp": 1,
                            "coordinates.radec_geojson.coordinates": 1,
                        },
                    }
                },
                "filter": {},
            },
        }
```

**Comment by Theodlz** [comment]
Hi @bfhealy . Why not specify thag min number of detections in the query itself, maybe it might help constrain it a bit? I believe you can do: `"candidate.ndethist": {"$gte": 2}` to filter based on that?

**Comment by Theodlz** [comment]
Unless that is not available in Gaia, but if my understanding is correct its a variation of Kowalski so it might have that field as well.

**Comment by bfhealy** [comment]
Thanks @Theodlz, if that doesn't work I can modify a previous query to the ZTF_sources catalog and filter by the number of detections there. I'll give this a try and see how it speeds things up.

**Comment by Theodlz** [comment]
I agree that filtering upstream is best. Also, you can consider running the queries in parallel to divide the runtime by how many cores you have available. There is the code for that in penquins.

**Comment by bfhealy** [comment]
Thanks, I hadn't looked into the parallel query code yet but it seems to be helping.
