### ISSUE TITLE
Memory leak during periodfind loops

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#309]
Although #307 put a limit on the number of light curves concurrently passed to `periodfind` algorithms, there still appears to be a memory leak within this loop in `generate_features.py`:

```
for i in range(0, n_iterations):
                    print(f"Iteration {i+1} of {n_iterations}...")
                    periods, significances, pdots = periodsearch.find_periods(
                        algorithm,
                        tme_collection[
                            i
                            * period_batch_size : min(
                                n_sources, (i + 1) * period_batch_size
                            )
                        ],
                        freqs,
                        batch_size=period_batch_size,
                        doGPU=doGPU,
                        doCPU=doCPU,
                        doSaveMemory=False,
                        doRemoveTerrestrial=doRemoveTerrestrial,
                        doUsePDot=False,
                        doSingleTimeSegment=False,
                        freqs_to_remove=freqs_to_remove,
                        phase_bins=20,
                        mag_bins=10,
                        doParallel=doParallel,
                        Ncore=Ncore,
                    )

                    all_periods = np.concatenate([all_periods, periods])
                    all_significances = np.concatenate(
                        [all_significances, significances]
                    )
                    all_pdots = np.concatenate([all_pdots, pdots])
```

It seems unlikely that updating the `all_periods`, `all_significances` and `all_pdots` arrays would be enough to fill 256G of memory. Running `top` shows a continually increasing `%MEM` as the loop runs, e.g.:
```
PID     USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                          
3401087 bhealy    20   0  259.3g 253.1g 377276 R  99.7  67.2  54:26.00 python 
```

Eventually, the process is killed:
```
Iteration 81 of 150...
Period finding lightcurves...
Number of lightcurves: 100
Max length of lightcurves: 174
Batch size: 100
Number of frequency bins: 8406506
Number of phase bins: 20
Number of magnitude bins: 10
Killed
```

**Comment by mcoughlin** [comment]
@bfhealy This is on the GPU?

**Comment by bfhealy** [comment]
@mcoughlin Yes, this is on the GPU despite the `%CPU` column in the `top` output.

**Comment by mcoughlin** [comment]
@bfhealy And do you find this on all the algorithms? Or can you isolate it to one?

**Comment by bfhealy** [comment]
@mcoughlin So far it's happening for the ECE algorithm, but that's because it's the first in the loop. I'll try starting with EAOV and ELS as well.

**Comment by bfhealy** [comment]
@mcoughlin Each of the ECE, EAOV and ELS algorithms are behaving similarly with a ramp-up in memory usage as the `periodsearch` loop progresses. I tried adding `del periods, significances, pdots` at the end of each iteration to no avail.

**Comment by mcoughlin** [comment]
@bfhealy can you make a minimal use case with just the library? We can try asking the guy who originally wrote it to see if he has any quick ideas with that.

**Comment by bfhealy** [comment]
@mcoughlin Sure, I'll try to replicate the issue just by calling periodfind directly for some data.
