### ISSUE TITLE
Missing sample CVs

### ISSUE THREAD

**Issue by dmitryduev** [ZwickyTransientFacility/scope#32]
Sample objects for the CV subclasses are missing in config.defaults.yaml, which results in empty plots [here](https://scope.ztf.dev/field_guide.html#id20).

**Comment by cjol245** [comment]
I changed the default.config file to include the CV sample objects and pushed to github; did it work? Absolute worst case I can send you the object coordinates.

**Comment by dmitryduev** [comment]
Not sure I understand what you mean. Please post the coordinates here, that would be the easiest thing to do, I guess.

**Comment by cjol245** [comment]
Sure. Listed as title:coordinates, in the order we would prefer.
CV U Gem: [18.884181, 37.626534]
CV Z Cam: [269.093260, 2.967803]
CV SU UMa: [170.883476, 43.288214]
CV Novalike: [322.961689, 49.233813]

Period = none for all

**Comment by bfhealy** [comment]
Closing, addressed by #36.
