### ISSUE TITLE
add new Fritz classification scheme to label uploaded sets

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#55]
A new 'classification' structure needs to be uploaded (and regularly updated) in order to label our uploads. For example; classifications called 'XGB high confidence RR lyrae", or "DNN high confidence RR lyrae".

**Comment by bfhealy** [comment]
The Fritz sitewide taxonomy ([timedomain-taxonomy](https://github.com/profjsb/timedomain-taxonomy), ID 1011) is now up-to-date with the scope ontological labels, and I have uploaded a new taxonomy ([scope-phenomenology](https://github.com/bfhealy/scope-phenomenology), ID 1012) that contains the scope phenomenological labels. The combination of these two taxonomies can be used to map scope dataset labels to Fritz (e.g. using golden_dataset_mapper.json in this repo).
