### ISSUE TITLE
python/jupyternotebook code to upload examples including tags

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#56]
We need an easy to use and flexible python function to upload a set of examples. This includes uploading the set, but also labelling the uploaded set appropriately. Most of this functionality is already there, but we need to make sure that it works under all circumstances; e.g. what happens if a source already exists etc.

**Comment by bfhealy** [comment]
The present versions of scope_upload_classification.py and scope_manage_annotation.py address these requests, since they upload and check for duplicate sources, classifications, photometry, annotations and comments.
