### ISSUE TITLE
upload labels from the D15 label set to Fritz

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#57]
The D15 training set is only available as a CSV files. We need to make sure it is uploaded to Fritz so we have all labels there.

**Comment by bfhealy** [comment]
The golden dataset is ready to upload (pending Fritz taxonomy updates, #55). I have dropped duplicate sources with disagreeing labels and sources with no Gaia EDR3 ID assigned.

As an example of how things will look on Fritz, I uploaded the collection of 2419 stars classified as delta Scuti to the 'golden_deltaScuti' group. Going forward, we'll have to determine whether to upload all golden sources to a single group or spread them among different groups by feature.

**Comment by bfhealy** [comment]
The golden dataset is available on Fritz in group 1458 ("Golden Dataset Unique Sources") containing 80,034 sources. Each source includes ontological labels from the [Sitewide Taxonomy](https://github.com/profjsb/timedomain-taxonomy) and phenomenological labels from the [SCoPe Phenomenological Taxonomy](https://github.com/bfhealy/scope-phenomenology).

This set of sources excludes those having no Gaia EDR3 ID, duplicate Gaia or ZTF IDs, or positions within 2 arcsec of another source in the original dataset. Sources having multiple rows with conflicting classifications were also excluded from the posted dataset.
