### ISSUE TITLE
script to download labels from Fritz and generate a trainingset

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#58]
The goal is to have a python script to downloads all available labels from Fritz and collects their features and puts it in an easy to use .csv file. The format of this file should be the same as the older d15 trainingset.

**Comment by mcoughlin** [comment]
We need to assess to what extent https://github.com/ZwickyTransientFacility/scope/blob/main/tools/scope_download_classification.py
is sufficient for this. It does not download the features from kowalski, which can be queried as here:
https://github.com/mcoughlin/ztfperiodic/blob/master/ztfperiodic/utils.py#L1789

This should be made to be an option in the code.

**Comment by bfhealy** [comment]
I think it's a good idea to incorporate Saagar's incoming get_features.py code (#84) into scope_download_classification.py to achieve this goal.
