### ISSUE TITLE
add folded lightcurves to the 'group' page

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#59]
We need to be able to see the folded lightcurve on the 'group' page, instead of clicking on the objects and having to open a new window. This needs to be done in skyportal.

**Comment by mcoughlin** [comment]
@janvanroestel Do you mean the source table page?

**Comment by AshishMahabal** [comment]
I see that the phased light curves are now seen on the group page. Thats is great (and very helpful).
I noticed that not all sources have the phased light curves though. Any idea why? I have attached a picture. (what is the "0" following the "No spectra exist"?)

Also, can we add the period itself - may be on the x-label, or the top-label?

(Is what is called DR8 the DR8 of SDSS or ZTF? That should be clarified in that figure's caption).

<img width="1146" alt="Screen Shot 2022-03-07 at 10 18 18 AM" src="https://user-images.githubusercontent.com/2147555/157110917-2d8ae62a-f051-4f1e-9718-eddfb8140181.png">

**Comment by mcoughlin** [comment]
@AshishMahabal Not all objects have a period annotation, they need annotations well to appear.

**Comment by bfhealy** [comment]
It looks like this issue has been mostly addressed in Skyportal, since I can view folded light curves in the source dropdown. The default period (= 1 d) for sources without an uploaded period will ensure this panel is always displayed if photometry is available. Period annotations are also shown in the dropdown. Ashish's question about DR8 (SDSS or ZTF?) remains, though.

**Comment by mcoughlin** [comment]
@bfhealy I think we should either rename the issue or close this one and open another. It is challenging of course if one issue has multiple different things reported.

**Comment by bfhealy** [comment]
I agree, I think it's best to close this one and open another. Should the new one be posted to Skyportal instead of here?

**Comment by mcoughlin** [comment]
@bfhealy agreed.
