### ISSUE TITLE
PS1 cutout and photometry "alternately" missing

### ISSUE THREAD

**Issue by AshishMahabal** [ZwickyTransientFacility/scope#61]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
When object details are loaded through expanding the '>' sign on the left, various cutouts are loaded among other things. The PS1 cutout does not appear. Once you click on the object id, it opens in the new page, and now it is seen in the original page too, but the photometry has vanished. See the before and after screenshots below.

**To Reproduce**
Go to https://fritz.science/group_sources/371 and do as suggested above

**Expected behavior**
PS1 cutout should load at the start. Photometry should not vanish.

**Screenshots**
<img width="928" alt="Screen Shot 2022-01-26 at 4 49 58 PM" src="https://user-images.githubusercontent.com/2147555/151271802-d00b6dd5-3c3e-4a58-bc5c-dd8b713cb939.png">
<img width="1015" alt="Screen Shot 2022-01-26 at 4 50 55 PM" src="https://user-images.githubusercontent.com/2147555/151271821-770f9cb5-d3d7-4012-8c82-f4239d37e1e2.png">

**Platform information:**
Chrome on Mac

**Additional context**
Program 371: https://fritz.science/group_sources/371

**Comment by mcoughlin** [comment]
should be solved on next deploy based on above. please reopen if not.
