### ISSUE TITLE
Generate a .csv trainingset from labels in Fritz

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#65]
code is needed to take the classifications from Fritz, clean them, put them in the correct format and add the features

**Feature Summary**
The input are labels from Fritz, and the main (single) output should be a .csv file that is the same format as the D15 trainingset.

The code should
- download objects and labels from Fritz
- download and combine labels from multiple groups on Fritz
- handle duplicate objects and labels
- verify the upstream labels (e.g. a delta scuti should be variable and periodic)
- get the features per lightcurves and join the with the labels
- save everything as a .csv file (exactly the same format as d15). Add a header that specifies the code version, and time of download from Fritz

**Comment by bfhealy** [comment]
While we now have code that downloads sources from Fritz, merges features from Kowalksi, and saves the output, there are still some points in this issue that need addressing: verifying upstream labels, adding a header, and saved file format (csv or hdf5?)

**Comment by bfhealy** [comment]
I am closing this issue and opening three new ones (#128, #129, #130) to separate the remaining action items.
