### ISSUE TITLE
zsh: illegal hardware instruction

### ISSUE THREAD

**Issue by marc-shen** [ZwickyTransientFacility/scope#67]
```zsh
(scope-env) user@user's MacBook-Pro scope-main % ./scope.py
zsh: illegal hardware instruction  ./scope.py
```
After I have completed the environment configuration according to the tutorial, I found that this environment can not operate normally under the arm64 architecture, which will be the same as the above.
```zsh
(scope-env) user@user's MacBook-Pro % uname -m
arm64
```
The computer is MacBook Pro 2021 with M1 pro CPU.

**Comment by mcoughlin** [comment]
@marc-shen can you please try the same thing in a conda environment?

**Comment by marc-shen** [comment]
Yes, I've already tried it.
I'm not sure which Python packages don't support the arm64 architecture.

**Comment by mcoughlin** [comment]
Yeah for M1 with tensorflow we need to play more tricks:

https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook

Can you give this a try and then if it works, we should update the docs with some brief instructions?

**Comment by marc-shen** [comment]
Thank you for your help.
I'm trying this method to solve the problem. However, limited to the network environment and this scheme, I want to adjust the python environment, and I can't feed back the results of my attempt in time.
This website `https://developer.apple.com/metal/tensorflow-plugin/` provides me with some useful information. I hope it will solve the problem.😀

**Comment by mcoughlin** [comment]
Ok let us know how it goes @marc-shen, clearly if you get it working, docs need a specific section for this.

**Comment by marc-shen** [comment]
@mcoughlin I have made many attempts in the past two days. At present, I can run the code `./scope.py` without errors.
Although there are some deficiencies in the solution you provided before, it has provided crucial help for my successful attempt.
These days, I will try to see if it works properly. I will write a document to briefly describe the problems I encountered and give my attempts. At the same time, I will also give some precautions that may be used.

**Comment by mcoughlin** [comment]
Thanks @marc-shen. Assuredly super useful.

**Comment by marc-shen** [comment]
# The solution in Mac system based on M1(ARM64)

## Issue

```zsh
(scope-env) user@user's MacBook-Pro scope-main % ./scope.py
zsh: illegal hardware instruction  ./scope.py
```

## Solution

In fact, the essence of the problem lies in tensorflow, a Python package.

We are supposed to install the correct version. Specifically, it should fit the ARM64 architecture, and the MacOs based on M1 CPU.

Apple official provides effective version. At this page `https://developer.apple.com/metal/tensorflow-plugin/` we can gain the methods to finish it.

But there are still some key things.

1. Anaconda doesn't work properly. In its place, We're going to use Miniforge3, also a conda environment, which is specifically adapted to Apple's operating system. Anaconda does not provide the correct version.

2. After we have successfully installed tensorflow-deps, tensorflow-macos, tensorflow-metal, we are going to modify the file `requirements.txt`before we install any other software. We are supposed to remove `tensorflow<2.6` `tensorflow-addons>=0.12` from `.ruquirements/dev.txt` .

   Then, we can use `pip install -r requirements.txt` to install other python packages.

   When we meet an error, we can install it by `conda install xxx` , and remove it from `.ruquirements/dev.txt` . After that, we use `pip install -r requirements.txt` again.

3. If some packages keep making errors.  We are supposed to update the conda environment.

## Suggestion

We hope that the official can provide the conda version of the `requirements.txt` , for the reason that the current version is only suitable for pip.

**Comment by mcoughlin** [comment]
@marc-shen Did you keep track of what your requirements file looks like with the problematic packages removed? Maybe we can make a pull request with .requirements/dev-M1.txt or similar?

**Comment by marc-shen** [comment]
To install the tensorflow for Mac OS 
```zsh
conda install -c apple tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
```

The `.requirements/dev-M1.txt`
```txt
deepdiff>=5.0
gsutil>=4.60
keras-tuner>=1.0.2
matplotlib>=3.3
pytest>=6.1.2
questionary>=1.8.1
scikit-learn>=0.24.1
wandb>=0.12.1
```

We need to install some packages separately.
```zsh
conda install numpy
conda install openblas #to fix the numpy
conda install healpy
conda install pandas
```

**Comment by mcoughlin** [comment]
@marc-shen nice. Can you open a PR with this requirements file and a summary of what you wrote in the installation docs?

**Comment by marc-shen** [comment]
@mcoughlin  Yes, I have opened a PR, but it's the first time that I have used this function. I'm not sure I'm following the GitHub community's basic etiquette or making any mistakes.

**Comment by mcoughlin** [comment]
@marc-shen we are all learning :)
