### ISSUE TITLE
Field guide section on Cepheid variables

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#9]
A field guide entry of Cepheid variables is needed

Feature Summary
write a description, show an example light curve, and add the golden set

Usage / behavior
similar to RRLyr page

Implementation details
See https://scope.ztf.dev/developer.html#contributing-field-guide-sections

**Comment by mcoughlin** [comment]
For reference, the Zooniverse field guide has:

## [Cepheids](https://en.wikipedia.org/wiki/Cepheid_variable)
 - Moderate amplitude (~0.3 to 0.8 mag)
 - Intermediate periods (log Period between ~0.3–1.5)
 - smooth, sawtooth variations (blue/green filters show stronger sawtooth pattern)

Cepheids are classic pulsating stars (i.e., they are stars passing through the [instability strip](https://en.wikipedia.org/wiki/Instability_strip)). As these stars expand and contract (i.e. pulsate) their size and temperature changes leading to regular, smooth variations in their brightness. Cepheids are yellow giants (i.e. they are large *and* hotter than Mira variables), taking a moderate amount of time to expand and contract (typically anywhere from 1-3 days to as many as 100 days in extreme cases).

**Comment by dmitryduev** [comment]
Addressed in #20, closing.
