### ISSUE TITLE
Enable photometry downloads

### ISSUE THREAD

**Issue by bfhealy** [ZwickyTransientFacility/scope#96]
**Feature Summary**
We currently have code to make and upload photometry (within fritz.py, called by scope_upload_classification.py). It would also be helpful to have the ability to programmatically download photometry.

**Usage / behavior**
This functionality could be implemented within scope_download_classification.py, toggled by an optional keyword. It should save the user's requested photometry locally.

**Implementation details**
This may need to be implemented in the section of the code that loops over each individual source. I am not aware of a current way to download photometry in bulk for multiple sources.

**Comment by mcoughlin** [comment]
@bfhealy Theo has code here for this: https://github.com/Theodlz/skyportal-dumps/blob/main/dump_skyportal.py#L741 that should be easy enough to incorporate.
